[package]
name = "md-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
md-engine = { path = "../md-engine" }
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
